### ISSUE TITLE
Crash on giving notification access

### ISSUE THREAD

**Issue by shipsywor** [rock3r/bundel#4]
**Describe the bug**
App crashes on giving notification access

**To Reproduce**
1. Open project in Android Studio.
2. Run it on Emulator API 29 or API 30
3. Give notification access to the app on device
4. App Crashes

Error via logcat:
```
2021-05-14 14:38:24.583 11014-11014/dev.sebastiano.bundel E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.sebastiano.bundel, PID: 11014
    java.lang.RuntimeException: Tried to marshall a Parcel that contained Binder objects.
        at android.os.Parcel.nativeMarshall(Native Method)
        at android.os.Parcel.marshall(Parcel.java:552)
        at dev.sebastiano.bundel.storage.NotificationsCache.toByteArray(NotificationsCache.kt:53)
        at dev.sebastiano.bundel.storage.NotificationsCache.writeToFile(NotificationsCache.kt:44)
        at dev.sebastiano.bundel.storage.NotificationsCache.storeStatusBarNotification(NotificationsCache.kt:36)
        at dev.sebastiano.bundel.storage.RobertoRepository$saveNotification$2.invokeSuspend(RobertoRepository.kt:24)
```

**Expected behavior**
To not crash

**Comment by rock3r** [comment]
Thanks for the report! We're aware, the app crashes not because of the permission but because we were trying to store notifications in a bad way. We'll fix this on Sunday's stream :)

**Comment by rock3r** [comment]
We've fixed it now :)
